### ISSUE TITLE
No instructions how to install/use

### ISSUE THREAD

**Issue by Spam1985** [crskycode/msLTBImporter#2]
This is exactly what I was looking for! However, I do not know how to install it correctly for Milkshape.  I placed the files in Milkshape's folder, but when I launch Milkshape, I see no option to import .ltb files.

**Comment by crskycode** [comment]
Just put the dll into Milkshape folder.
If it's not work, try install visual C++ redistributable.

**Comment by Spam1985** [comment]
Hi! Sorry if I'm being stupid. I do not see any .ddl here. I tried to build it using Visual C++ but I got all sorts of errors.

**Comment by crskycode** [comment]
Download DLL from Releases

**Comment by Spam1985** [comment]
Got it, thanks! Unfortunately it doesn't work for Die Hard: Nakatomi Plaza's .LTB files. I've been trying to open these for a while but nothing works. Thanks anyway!
